name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome 👋 to the easyNeuron community, it looks like this is your first issue here! Please make sure you follow our [Code of Conduct](https://github.com/Neuron-AI/easyNeuron/blob/main/.github/CODE_OF_CONDUCT.md) and our [Contributing Guidelines](https://github.com/Neuron-AI/easyNeuron/blob/main/.github/CONTRIBUTING.md).'
        pr-message: 'Welcome 👋 to the easyNeuron community, thanks for contributing your first pull request! Please make sure you follow our [Code of Conduct](https://github.com/Neuron-AI/easyNeuron/blob/main/.github/CODE_OF_CONDUCT.md) and our [Contributing Guidelines](https://github.com/Neuron-AI/easyNeuron/blob/main/.github/CONTRIBUTING.md).'
