name: Test Python

on:
  pull_request:
    branches: [ main ]

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - name: Test Python
      - run: python -m unittest  Tests/test_easyNeuron.py
    
